# Generated by Django 5.2.7 on 2025-10-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom du champ")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("string", "String"),
                            ("text", "Text"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                            ("decimal", "Decimal"),
                            ("foreign_key", "Foreign Key"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_primary_key", models.BooleanField(default=False)),
                ("is_nullable", models.BooleanField(default=True)),
                ("is_unique", models.BooleanField(default=False)),
                ("default_value", models.CharField(blank=True, max_length=255)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Champ",
                "verbose_name_plural": "Champs",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du schéma"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "schema_definition",
                    models.JSONField(verbose_name="Définition du schéma"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposé"),
                            ("modified", "Modifié"),
                            ("validated", "Validé"),
                            ("implemented", "Implémenté"),
                            ("rejected", "Rejeté"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database_schemas",
                        to="documents.document",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schéma de base de données",
                "verbose_name_plural": "Schémas de bases de données",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom de la table"),
                ),
                ("description", models.TextField(blank=True)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="database_manager.databaseschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("one_to_one", "One to One"),
                            ("one_to_many", "One to Many"),
                            ("many_to_many", "Many to Many"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="database_manager.databasefield",
                    ),
                ),
                (
                    "to_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="database_manager.databasefield",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="database_manager.databaseschema",
                    ),
                ),
                (
                    "from_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_from",
                        to="database_manager.databasetable",
                    ),
                ),
                (
                    "to_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_to",
                        to="database_manager.databasetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation",
                "verbose_name_plural": "Relations",
            },
        ),
        migrations.AddField(
            model_name="databasefield",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="database_manager.databasetable",
            ),
        ),
        migrations.CreateModel(
            name="ExternalDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de la connexion"
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("sqlite", "SQLite"),
                            ("mssql", "Microsoft SQL Server"),
                            ("oracle", "Oracle"),
                        ],
                        max_length=50,
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("database_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connecté"),
                            ("disconnected", "Déconnecté"),
                            ("error", "Erreur"),
                        ],
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                ("last_connection_test", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("imported_schema", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_databases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Base de données externe",
                "verbose_name_plural": "Bases de données externes",
            },
        ),
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(verbose_name="Requête SQL")),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "execution_time",
                    models.FloatField(
                        default=0.0, verbose_name="Temps d'exécution (s)"
                    ),
                ),
                ("rows_affected", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "external_db",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_history",
                        to="database_manager.externaldatabase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="db_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de requête",
                "verbose_name_plural": "Historiques de requêtes",
                "ordering": ["-created_at"],
            },
        ),
    ]
