# Generated by Django 5.2.7 on 2025-10-30 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_manager", "0001_initial"),
        ("documents", "0002_documentanalysis_confidence_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        help_text="JSON contenant les données du document formatées selon le schéma",
                        verbose_name="Données extraites",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("extracted", "Extrait"),
                            ("validated", "Validé"),
                            ("rejected", "Rejeté"),
                            ("imported", "Importé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Score de confiance de l'extraction (0-1)",
                        verbose_name="Score de confiance",
                    ),
                ),
                (
                    "extraction_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes générées par l'IA sur l'extraction",
                        verbose_name="Notes d'extraction",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_extractions",
                        to="documents.document",
                        verbose_name="Document source",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_extractions",
                        to="database_manager.databaseschema",
                        verbose_name="Schéma cible",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_extractions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Extraction de données",
                "verbose_name_plural": "Extractions de données",
                "ordering": ["-created_at"],
            },
        ),
    ]
