# Generated by Django 5.2.7 on 2025-10-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("database_manager", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Titre de la conversation"
                    ),
                ),
                (
                    "use_documents",
                    models.BooleanField(
                        default=True, verbose_name="Utiliser les documents"
                    ),
                ),
                (
                    "use_external_db",
                    models.BooleanField(
                        default=False, verbose_name="Utiliser la base externe"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="conversations",
                        to="documents.document",
                    ),
                ),
                (
                    "external_db",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="database_manager.externaldatabase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Utilisateur"),
                            ("assistant", "Assistant"),
                            ("system", "Système"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="Tokens utilisés"),
                ),
                (
                    "response_time",
                    models.FloatField(default=0.0, verbose_name="Temps de réponse (s)"),
                ),
                ("sources_used", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Note (1-5)",
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(blank=True, null=True, verbose_name="Utile?"),
                ),
                (
                    "is_accurate",
                    models.BooleanField(blank=True, null=True, verbose_name="Précis?"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
            },
        ),
        migrations.CreateModel(
            name="QueryContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu du contexte")),
                (
                    "relevance_score",
                    models.FloatField(verbose_name="Score de pertinence"),
                ),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("chunk_index", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_contexts",
                        to="documents.document",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contexte de requête",
                "verbose_name_plural": "Contextes de requêtes",
                "ordering": ["-relevance_score"],
            },
        ),
    ]
