# Generated by Django 5.2.7 on 2025-11-07 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("documents", "0003_documentcontent_pdf_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="generated/%Y/%m/%d/", verbose_name="Fichier généré"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("txt", "Text"),
                            ("json", "JSON"),
                            ("csv", "CSV"),
                        ],
                        max_length=10,
                        verbose_name="Type de fichier",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="Taille (bytes)"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du fichier"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "tool_used",
                    models.CharField(
                        choices=[
                            ("compare", "Comparaison de documents"),
                            ("merge", "Fusion de documents"),
                            ("generate", "Génération personnalisée"),
                            ("extract", "Extraction d'informations"),
                        ],
                        max_length=20,
                        verbose_name="Outil utilisé",
                    ),
                ),
                (
                    "generation_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Paramètres de génération",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "downloaded_count",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_files",
                        to="chat.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_files",
                        to="chat.message",
                        verbose_name="Message associé",
                    ),
                ),
                (
                    "source_documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="generated_from",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier généré",
                "verbose_name_plural": "Fichiers générés",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("context", "Contexte"),
                            ("source", "Source"),
                            ("target", "Cible"),
                        ],
                        default="context",
                        max_length=20,
                        verbose_name="Rôle du document",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.message",
                        verbose_name="Ajouté par le message",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_documents",
                        to="chat.conversation",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_conversations",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de conversation",
                "verbose_name_plural": "Documents de conversation",
                "ordering": ["added_at"],
                "unique_together": {("conversation", "document")},
            },
        ),
    ]
