# Generated by Django 5.2.7 on 2025-10-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du document"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/", verbose_name="Fichier"
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=50)),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="Taille (bytes)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours d'analyse"),
                            ("completed", "Analysé"),
                            ("error", "Erreur"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Résumé")),
                ("entities", models.JSONField(blank=True, default=dict)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("structure", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse du document",
                "verbose_name_plural": "Analyses des documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="Index du segment")),
                ("content", models.TextField(verbose_name="Contenu du segment")),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("start_char", models.IntegerField(blank=True, null=True)),
                ("end_char", models.IntegerField(blank=True, null=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment de document",
                "verbose_name_plural": "Segments de documents",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField(verbose_name="Texte brut extrait")),
                (
                    "processed_text",
                    models.TextField(blank=True, verbose_name="Texte traité"),
                ),
                ("word_count", models.IntegerField(default=0)),
                ("page_count", models.IntegerField(default=0)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("embeddings", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenu du document",
                "verbose_name_plural": "Contenus des documents",
            },
        ),
    ]
