# Generated by Django 5.2.7 on 2025-10-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentanalysis",
            name="confidence_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Score de confiance"
            ),
        ),
        migrations.AddField(
            model_name="documentanalysis",
            name="detected_document_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Type de document"
            ),
        ),
        migrations.AddField(
            model_name="documentanalysis",
            name="language",
            field=models.CharField(blank=True, max_length=50, verbose_name="Langue"),
        ),
    ]
