# Generated by Django 5.2.7 on 2025-11-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documentanalysis_confidence_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontent",
            name="pdf_structure",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Structure PDF extraite"
            ),
        ),
    ]
